services:
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: sprig-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-sprig_db}
      APP_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sprigapp-network

  mysql:
    image: mysql:8.4
    container_name: sprig-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-sprig_db}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:Z
    networks:
      - sprigapp-network
    deploy:
      resources:
        limits:
          # Testing Environment (ubah pas udah di deploy)
          cpus: '1.0'
          memory: 2048M

  adminer:
    image: adminer:latest
    container_name: sprig-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_USER: ${DB_USERNAME:-root}
      ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD:-root}
    depends_on:
      - mysql
    networks:
      - sprigapp-network
    deploy:
      resources:
        limits:
          # Testing Environment (ubah pas udah di deploy)
          cpus: '0.1'
          memory: 64M

  migrate:
    image: migrate/migrate
    container_name: sprigapp_migration-tools
    profiles: [ "tools" ]
    volumes:
      - ./migrations:/migrations
    networks:
      - sprigapp-network
    depends_on:
      - mysql

  test:
    image: golang:1.26-alpine
    container_name: sprigapp_test-tools
    working_dir: /app
    profiles: [ "tools" ]
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-sprig_db}
    depends_on:
      - mysql
    networks:
      - sprigapp-network

volumes:
  dbdata:

networks:
  sprigapp-network:
    driver: bridge
